In [1]:
import torch

## Tensores

### Declarar tensores

In [54]:
A = torch.rand([3,2,5])
A

tensor([[[0.3312, 0.0467, 0.6403, 0.4254, 0.4847],
         [0.0163, 0.8568, 0.4804, 0.1518, 0.3412]],

        [[0.5841, 0.3072, 0.0948, 0.5604, 0.5875],
         [0.0032, 0.3150, 0.9400, 0.3888, 0.2111]],

        [[0.8638, 0.0130, 0.9183, 0.6790, 0.1457],
         [0.2523, 0.9692, 0.0392, 0.8305, 0.1512]]])

In [15]:
# Ver el tamaño de un tensor
A.size()

torch.Size([8, 3, 5])

In [28]:
# Ver el tipo de los elementos de un tensor
A.dtype

torch.float32

**Seleccionar elementos de un tensor**

In [19]:
A[0][0][0]

tensor(0.6154)

In [20]:
A[0,0,0]

tensor(0.6154)

In [22]:
A[0,0]

tensor([0.6154, 0.3473, 0.1410, 0.3905, 0.9149])

In [21]:
A[0,:,0]

tensor([0.6154, 0.6064, 0.1557])

In [30]:
# Generar un tensor de ceros
C = torch.zeros([4,2])
C

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [43]:
# Crear un tensor con números enteros, el primer parametro define el valor máximo que recibira
D = torch.randint(9,[4,2])
D

tensor([[3, 8],
        [8, 6],
        [0, 2],
        [6, 2]])

In [52]:
# Operaciones entre tensores (+, -, *, /, **)
C + D

tensor([[0., 0.],
        [0., 0.],
        [1., 0.],
        [0., 0.]])

In [46]:
# Ver en que parte esta alojado un vector
C.device

device(type='cpu')

In [48]:
torch.cuda.is_available()

False