# Tensores

## Librerias

In [2]:
import torch

## Declarar tensores

In [4]:
A = torch.rand([3,2,5])
A

tensor([[[0.8851, 0.0299, 0.5156, 0.3811, 0.8771],
         [0.4191, 0.2468, 0.4701, 0.7994, 0.8883]],

        [[0.3644, 0.0341, 0.3697, 0.4710, 0.9376],
         [0.4518, 0.1411, 0.6675, 0.2882, 0.1034]],

        [[0.0076, 0.8067, 0.6913, 0.3724, 0.7183],
         [0.0612, 0.3477, 0.9863, 0.7114, 0.9110]]])

In [5]:
# Ver el tamaño de un tensor
A.size()

torch.Size([3, 2, 5])

In [6]:
# Ver el tipo de los elementos de un tensor
A.dtype

torch.float32

**Seleccionar elementos de un tensor**

In [7]:
A[0][0][0]

tensor(0.8851)

In [8]:
A[0,0,0]

tensor(0.8851)

In [9]:
A[0,0]

tensor([0.8851, 0.0299, 0.5156, 0.3811, 0.8771])

In [10]:
A[0,:,0]

tensor([0.8851, 0.4191])

In [11]:
# Generar un tensor de ceros
C = torch.zeros([4,2])
C

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [12]:
# Crear un tensor con números enteros, el primer parametro define el valor máximo que recibira
D = torch.randint(9,[4,2])
D

tensor([[2, 6],
        [3, 5],
        [8, 5],
        [4, 5]])

In [13]:
# Operaciones entre tensores (+, -, *, /, **)
C + D

tensor([[2., 6.],
        [3., 5.],
        [8., 5.],
        [4., 5.]])

### **CPU vs GPU**

In [14]:
# Ver en que parte esta alojado un vector
C.device

device(type='cpu')

In [15]:
# Ver si la opción de usar la GPU esta disponible
torch.cuda.is_available()

True

In [16]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [18]:
# Tensor en CPU
x = torch.randn([3, 5])
x

tensor([[-0.2408, -0.6162,  1.2911,  1.4767, -0.5898],
        [ 0.0543, -0.5495, -2.2585, -1.2965, -0.7567],
        [ 0.7211, -0.9765,  1.2713, -1.9097,  0.3335]])

In [23]:
# Tensor en GPU
y = torch.ones_like(x, device=device)
y

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], device='cuda:0')

In [25]:
# Enviar un tensor de la CPU a la GPU

x = x.to(device)

In [28]:
# Ya podemos operar nuestros tensores (deben estar en el mismo sitio)
z = x + y

In [29]:
z

tensor([[ 0.7592,  0.3838,  2.2911,  2.4767,  0.4102],
        [ 1.0543,  0.4505, -1.2585, -0.2965,  0.2433],
        [ 1.7211,  0.0235,  2.2713, -0.9097,  1.3335]], device='cuda:0')

In [38]:
# z = z.to('cuda')
z = z.to('cpu')